<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyTitle>MaxHub Agent</AssemblyTitle>
    <AssemblyName>MaxHubAgent</AssemblyName>
    <Version>1.0.17</Version>
    <ApplicationIcon>Assets\maxhub.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\maxhub.ico" />
    <Resource Include="Assets\release-notes.zh-CN.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MaxHub.Agent.Core\MaxHub.Agent.Core.csproj" />
    <ProjectReference Include="..\MaxHub.Agent.Service\MaxHub.Agent.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

</Project>
